config/routes.rb
FbcamQgdoenem::Application.routes.draw do
  root :to => 'home#video'

  get '/video' => 'home#video', as: :video
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def video
		@channel = 14
	end

end

app/views/home/index.html.erb
<script type="text/javascript">
	$(document).on('fbload', checkLike);

	function checkLike(){
  	FB.login(function(response) {
  		FB.api('/me', function(resp) {

  			if (resp.id) {
			    var user_id = resp.id;
			    var page_id = "199601326870016";
			    var fql_query = "SELECT uid FROM page_fan WHERE page_id = "+page_id+"and uid="+user_id;
			    var the_query = FB.Data.query(fql_query);
			    the_query.wait(function(rows) {
			        if (rows.length == 1 && rows[0].uid == user_id) {
		            window.location = "<%= video_path %>"
			        }
			    });
			  }

	    });

	    /*FB.api('/me/likes/PAGE_ID',function(response) {
	    	if(response.data) {
	    		if(!isEmpty(response.data)){
	    			window.location = "<%= video_path %>"
	    		}
			  }else{
			  	// ERROR
			  }
			});
			 
			function isEmpty(obj) {
				for(var prop in obj) {
					if(obj.hasOwnProperty(prop))	return false;
			  }

			  return true;
			}*/
		});
  }

	function checkStatus(){
		FB.getLoginStatus(function(response) {
			if (response.status === 'connected') {
		    var uid = response.authResponse.userID;
		    var accessToken = response.authResponse.accessToken;
		    window.location = "<%= video_path %>"
		  }
		});
	}

	function authUser(){
		FB.login(function(response) {

		  if (response.authResponse) {
		    FB.api('/me', function(response) {
		    	checkStatus();
		    });
		  }

		}, {scope: 'email, user_likes'});
	}

</script>

<section class="general curtir">
	<!--div class="block_cntt pin">
		<img src="/assets/top_curtir.png">
	</div>

	<header>
		<a id="loginButton" onclick="authUser();">
			<img src="/assets/like_fb.png" width="15" height="15"/>&nbsp;
			<span>Curtir</span>
		</a>

		<h1 class="logo">
			<img src="/assets/logo_fcpeo.png" />
		</h1>
		<div class="col_02">
			<p class="line_01">ASSISTA <span>AO VIVO</span></p>
			<h2 class="line_03">REVISÃO PARA O ENEM</h2>
			<p class="line_04">TRANSMISSÃO DA GRAVAÇÃO DE AULA</p>
		</div>
	</header-->

	<section class="schedule">
		<img src="/assets/new/banner-nolike.jpg" />
	</section>

	<footer>
		<a href="http://www.enem.com.br/" target="_blank">www.enem.com.br</a>
	</footer>

	<div class="fb-comments" data-href="http://www.enem.com.br#qgdoenem-facecam-nolike" data-numposts="10" data-width="800"></div>
</section>

app/views/home/video.html.erb
<section class="general default_template sexta_impossivel">
	<section class="content">
		<div id="video_wpr_wpr">
			<div id='video' class="video">
				<!-- Video aqui -->
			</div>			
		</div>
	</section>

	<section class="newsletter_form">
		<div class="col_01">
			<p class="line_01">QUER RECEBER INFORMAÇÕES <br/>SOBRE O ENEM? </p>
			<p class="line_02">CADASTRE-SE AQUI PARA RECEBER AS <br/>ÚLTIMAS DICAS E INFORMAÇÕES PARA A PROVA.</p>
		</div>
		<div class="col_02">
				<form action="http://cers.mailee.me/go/add_contact_form" id="mailee-form" method="post">
					<input name="key" type="hidden" value="994119">
					<input name="url_ok" type="hidden" value="https://www.facebook.com/QGdoEnem/app_190322544333196">
					<input name="url_error" type="hidden" value="https://www.facebook.com/QGdoEnem/app_190322544333196">
					<input name="list[]" type="hidden" value="523864">

					<label for="txt_nome">Nome</label>
					<input name="name" type="text" class="txt" id="txt_nome" />
					<label for="txt_email">E-mail</label>
					<input name="email" type="text" class="txt" id="txt_email" />
					<input class="btn_submit" type="submit" value="Cadastrar" />
				</form>
		</div>
	</section>

	<footer>
		<a href="http://www.enem.com.br/" target="_blank">www.enem.com.br</a>
	</footer>

	<div class="fb-comments" data-href="http://www.enem.com.br#qgdoenem-facecam" data-numposts="10" data-width="800"></div>
</section>
		

<script type='text/javascript'>
	function sendURL(){}

	jwplayer("video").setup({
		flashplayer: '/assets/skins/player-licensed.swf',
		height: '354px',
		width: '640px',
		autostart: true,
		controlbar: 'bottom',
		dock : false,
		modes: [
		{ 
			type: 'flash', 
			src: "/assets/skins/player-licensed.swf", 
			config: { 
				skin : "/assets/skins/cers.zip",
				provider : "http://players.edgesuite.net/flash/plugins/jw/v2.11/jw5/AkamaiAdvancedJWStreamProvider.swf",
				file : "http://renatosaraiva-f.akamaihd.net/rsaraiva_1_<%= @channel %>@37037"
			}
		}, 
		{ 
			type: 'html5', 
			config: {
				skin : "/assets/skins/cers.xml",
				file : "http://rsaraiva_ios-i.akamaihd.net/hls/live/203931/cers<%= @channel %>/playlist.m3u8",
				provider : 'video'
			}
		}
		]
	});

	// function checkStatus(){
	// 	FB.getLoginStatus(function(response) {
	// 		//alert(response.status)
	// 	  if (response.status !== 'connected') {
	// 	    window.location = "<%= root_path %>"
	// 	  }
	// 	});
	// }

	// function checkLike(){
	// 	FB.api('/me', function(response) {
	// 		if (response.id) {
			    
	// 	    var user_id = response.id;
	// 	    var page_id = "199601326870016";
	// 	    var fql_query = "SELECT uid FROM page_fan WHERE page_id = "+page_id+"and uid="+user_id;
	// 	    var the_query = FB.Data.query(fql_query);
	// 	    the_query.wait(function(rows) {
	// 	        if (rows) {
	//             window.location = "<%= root_path %>"
	// 	        }
	// 	    });
	// 	  }
 //    });
 // }

	//$(document).on('fbload', checkLike);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>FacebookCam - QGdoEnem</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	
	<meta charset="utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
	<link href='https://fonts.googleapis.com/css?family=Ubuntu:300,300italic,400,400italic,500,700' rel='stylesheet' type='text/css'>
</head>
<body>
	<!-- Facebook Root -->
	<!-- ========================================================================================================== -->
	<div id="fb-root"></div>
	<script>
	  window.fbAsyncInit = function() {
	    FB.init({
	      appId      : '1393749097528499',                  					      // App ID from the app dashboard
	      channelUrl : 'http://fbcam-qgdoenem.herokuapp.com/',							// Channel file for x-domain comms
	      status     : true,							                                  // Check Facebook Login status
	      xfbml      : true               							                    // Look for social plugins on the page
	    });

		  $(document).trigger('fbload');  //  <---- THIS RIGHT HERE TRIGGERS A CUSTOM EVENT CALLED 'fbload'
		};

		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=1393749097528499";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	</script>
	<!-- ========================================================================================================== -->

	<!-- Google Analytics -->
	<!-- ========================================================================================================== -->
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-45103969-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
	<!-- ========================================================================================================== -->

	<%= yield %>

</body>
</html>